### ISSUE TITLE
A few issues & advise

### ISSUE THREAD

**Issue by hellolake** [crimx/crx-saladict#1]
Select a word and pressing CTRL can't auto load the selected word with ver. 5.0.

The popup animation is not a good experience, it takes so long to show and disappear.

Make a option in Settings to toggle animation if possible.

**Comment by crimx** [comment]
Could you provide the version of your system & chrome? CTRL works fine last time I checked. Make sure the "hold Ctrl" option is selected.

I'll look into the animation issue,.

**Comment by hellolake** [comment]
@crimx 
It doesn't work with Hold Ctrl/⌘, now everything work fine except this.

Saladict: 5.1.2
Chrome: 54.0.2840.98 & 57.0.2987.133
System:  MacOS 10.12.1

**Comment by crimx** [comment]
@hellolake Could you try this http://codepen.io/straybugs/full/PpgGEW/ and tell me which one turns green? Ideally both should work.

**Comment by hellolake** [comment]
@crimx 
Chrome 57.0.2987.133:
Nothing reacted via holding CTRL+click both of them, but sometimes it works.
Change to green then turn back via holding CMD+click both of them.

Chrome 54.0.2840.98:
Nothing reacted on the second one by CTRL+click, but works sometimes.
They work as ver.57 above by CMD+click.

**Comment by crimx** [comment]
@hellolake Looks like it's an individual case. The second one should always work. I've tested on both MacOS and Windows. You can try to click on this again and check the key codes. http://codepen.io/straybugs/full/PpgGEW/

**Comment by hellolake** [comment]
@crimx 
So be like that, it's not a big bad issue for me.
In your testing page, in first click, both CTRL&CMD, key&keycode is none both of them, the 2nd one didn't change to green, but they work in 2nd+ action.
Anyway, thanks for your reply.

**Comment by crimx** [comment]
@hellolake Sure. And key code with none means something wrong with your browser or keyboard. I think it's more likely with the browser. Probably other extension is messing with the key events.
