### ISSUE TITLE
能否增加生词本的生词来源页面以及上下文段落？

### ISSUE THREAD

**Issue by jerry011235** [crimx/crx-saladict#12]
1.在生词本页面，点击某个生词，弹出一个窗口，显示出：当时浏览时包含这个生词的上下文的整个段落，以及相应的网址。
2.当然，在添加生词时，可以弹出窗口，手动输入：包含这个生词的上下文的整个段落，甚至整篇文章。
3.最后可以按组导出为txt。
一个组包括：一个生词，生词翻译，上下文段落，（段落翻译），网址。

点击生词后，我知道上下文是什么，网址是什么，这样可以更快地记住单词。
目的很明显，学英语变得连贯起来了，而非一个一个单独的生词。

**Comment by crimx** [comment]
chrome 里存储的数据有限

**Comment by crimx** [comment]
发现申请 `unlimitedStorage` 权限可以获得无限空间，我再研究研究数据量大时对性能的影响。

**Comment by jerry011235** [comment]
如果不依赖 chrome 里的存储能行吗？做成chrome应用，或者干脆自定义一个文件夹存放。

**Comment by crimx** [comment]
不行，除非引入服务器。扩展其实就是网页来的，不能直接操作文件系统。APP 在非 Chrome OS 的支持已在放弃过程中。

**Comment by jerry011235** [comment]
那么在扩展文件夹里新建html文件呢，新建`……\User Data\Default\Extensions\cdonnmffkdaoajfknoeeecmchibpmkmg\5.28.1_0\salad.html`。
然后在生词本点击`salad`，，进入到
`chrome-extension://cdonnmffkdaoajfknoeeecmchibpmkmg/salad.html`
从上到下，依次是生词，生词翻译，上下文段落，（段落翻译），网址。

**Comment by crimx** [comment]
不是这么操作的，其实功能我已经实现了，在调样式中

**Comment by crimx** [comment]
上下文和来源的查看已经实现好了，感兴趣可以尝鲜试一下有无问题，[dist.zip](https://github.com/crimx/crx-saladict/files/1509932/dist.zip)，还剩导出功能这几天再实现。

**Comment by jerry011235** [comment]
Great！Excellent！
点赞！尤其是单词翻译默认留空，为了检测自己到底记没记住。还有笔记功能：）
另外似乎导出文件还没做好，还有上下文是现在这样就好，还是鼠标移过去再显示比较好？

**Comment by crimx** [comment]
好的！ 留空这个确实是这么设计的哈，还有一个原因是词典结果本身不能确定哪个是对应的翻译，所以既然有了上下文也不需要了。

**Comment by jerry011235** [comment]
建议：
1.上下文编辑，增加一个“段落翻译”，默认也留空，可以自己写入翻译。
2.语言支持那增加一个选项开关：中英文查词。
目前的情况是：鼠标选中的一句话里包含英文和中文时，它还是要显示翻译图标，即当作英文看待。

**Comment by crimx** [comment]
段落翻译这个放到笔记里即可，选项太多反而会影响效率。英文这个设置是故意的，不然识别一段句子会比较麻烦。

**Comment by crimx** [comment]
或许在原来两个选项的基础上再加入一个类似于 hard mode 的“单词模式”？感觉有点复杂。或者降低句子识别率兼容两者，hummm~

**Comment by crimx** [comment]
最后选择了在英文模式下再判断一下有没有中文

**Comment by jerry011235** [comment]
能否导出单个单词，而不是整个生词本里的单词都导出。
比如导出`salad`，编辑输入
```
%text% 
%trans%
%context%
%url%
```
后导出文件名为 `salad.txt`

**Comment by crimx** [comment]
这个貌似复制粘贴可以胜任，不知有什么应用场景？

**Comment by jerry011235** [comment]
单独导出某个或某些单词，随时打开txt，可以转存到手机，加深点印象。

**Comment by crimx** [comment]
还是不太清楚这个场景，文件通过什么方式转存到手机？还有每个单词一个文件应该会有大量文件，如何管理？

**Comment by crimx** [comment]
其实想在手机上学习推荐结合 ANKI 使用，跟导出功能完美搭配。

**Comment by jerry011235** [comment]
谢谢了，我去试下！
