### ISSUE TITLE
和Vimium插件冲突

### ISSUE THREAD

**Issue by qwertyyb** [crimx/crx-saladict#15]
和Vimium插件同时使用，在输入框中选中文本后，再点击输入框，不会取消选中，希望尽快修复这个问题

**Comment by crimx** [comment]
没有使用过 Vimium，请提供完整的操作方式重现冲突。我会尽量看看，尽管这个不能算是这个扩展的问题。

**Comment by qwertyyb** [comment]
![2](https://user-images.githubusercontent.com/16240729/33375560-4435f3de-d545-11e7-9ba6-8aff746b4000.gif)
扩展的问题，但是还是希望能尽量调整一下，避免这个问题

**Comment by qwertyyb** [comment]
不好意思， 尽管确实不能算是扩展的问题，还是希望能调整一下，最好能避免这个问题

**Comment by crimx** [comment]
这个应该不是这个扩展的问题，本扩展只是监测选择而已，不会改变选择。可以先在设置停用了本扩展之后看能取消选择么？

**Comment by crimx** [comment]
我安装了 Vimium ，没有发现这个冲突

**Comment by qwertyyb** [comment]
OK.我这边也测试过了，看来似乎是浏览器的问题，不好意思了

**Comment by crimx** [comment]
嗯，可能是其它冲突。
