### ISSUE TITLE
希望加入单词收藏，本地可导出就可以了

### ISSUE THREAD

**Issue by yyyyyyyhb** [crimx/crx-saladict#17]
使用相关的问题请确保先看了 Wiki 《划词翻译食用方式》 <https://github.com/crimx/crx-saladict/wiki> 。

不能划词的网站请提供具体链接。刚安装扩展后已经打开的页面需要刷新一遍以加载词典。

如果是查词结果不正确或无结果，请先点击结果左上的词典图标跳转到词典网页，查看是否为自身网络问题。

因安全问题，chrome 商店页面、自带的 PDF 页面以及其它扩展的页面是不能划词的。可用点击图标或三按 ctrl 快速查词，本扩展自带 PDF 阅读器。

**Comment by crimx** [comment]
请确保先看了 Wiki 《[划词翻译食用方式](https://github.com/crimx/crx-saladict/wiki#search-history)》
