### ISSUE TITLE
v5.29.3版 360 浏览器, 安装加载报错

### ISSUE THREAD

**Issue by lzpong** [crimx/crx-saladict#19]
![image](https://user-images.githubusercontent.com/10493371/33876785-7326808e-df61-11e7-824e-5e5677c326a9.png)

![image](https://user-images.githubusercontent.com/10493371/33874738-c90ff1d0-df5a-11e7-853b-27ab9e52c3d4.png)

**Comment by crimx** [comment]
这貌似是 360 浏览器的 bug，http://bbs.360.cn/forum.php?mod=viewthread&tid=15265606&page=1&cmpage=1


是用的9.0.1.152版本吗，尝试右键点击桌面上极速浏览器的图标-—属性—打开文件位置或者查找目标，点击上一级目录chrome，重命名User Data为 User Data12（如需保存本地收藏夹请提前导出）

**Comment by crimx** [comment]
[这里](https://www.v2ex.com/t/413130)提到貌似是谷歌商店新版打包的原因。不行的话解压 crx 包，将 `_metadata` 文件夹删除，然后用开发者模式加载用就行。等待官方看有什么解决方式。

**Comment by crimx** [comment]
@lzpong 用这个 [Saladict_v5.30.0.zip](https://github.com/crimx/crx-saladict/files/1551212/Saladict_v5.30.0.zip)

**Comment by lzpong** [comment]
不是 谷歌商店 下载的, 就是这里下载的: https://github.com/crimx/crx-saladict/releases/download/v5.30.0/Saladict_v5.30.0.crx

**Comment by crimx** [comment]
我发布的扩展都是从谷歌商店打包的，所以 ID 会保持一致。刚刚这个 zip 是利用上面提到的方式下载的，所以可以了。
