### ISSUE TITLE
可否加一个选项：打开小窗口的时候不自动查询剪贴板的内容

### ISSUE THREAD

**Issue by fengcen** [crimx/crx-saladict#2]
这个字典是现在我觉得最好用的，但是在使用小窗口查询的时候比较麻烦，因为我并不希望它自动查询剪贴板的内容。谢谢作者开发这个好用的插件。

**Comment by crimx** [comment]
嗯，一直也在对自动查词这个功能的体验优化，会在下个版本再加上开关。

**Comment by crimx** [comment]
更新 [v5.15.12](https://github.com/crimx/crx-saladict/releases/tag/v5.15.12)
