### ISSUE TITLE
路径含中文和##等无效：先用chrome打开本地pdf，再选择saladict打开为pdf无效

### ISSUE THREAD

**Issue by ljk8800** [crimx/crx-saladict#20]
如果pdf路径中含中文和##等，先用chrome打开本地pdf，再选择saladict打开为pdf无效
报错：
无效或损坏的PDF文件。
PDF.js v1.10.88 (build: c62a1938)
信息：Invalid PDF structure

**Comment by crimx** [comment]
本地 pdf 不能通过链接打开(不然也太不安全了，试想我知道路径就能访问你的操作系统文件)。请在 Saladict 的 pdf 内点击打开图标加载。

这个我以后再加个机制说明。

**Comment by ljk8800** [comment]
可是路径中不含中文和#这些符号是可以打开的╮(╯▽╰)╭

**Comment by crimx** [comment]
嗯，你是打开了“允许访问文件网址”是吧，我再优化一下这方面体验。

**Comment by ljk8800** [comment]
好的，多谢勤勉的作者

**Comment by crimx** [comment]
刚才已经修复了，来，帮忙测试一下开解决了没有，现在直接点击链接就可以打开。[dist.zip](https://github.com/crimx/crx-saladict/files/1554700/dist.zip)

**Comment by ljk8800** [comment]
先通过chrome打开pdf，再选择saladict打开为PDF还是不能还有特殊字符╮(╯▽╰)╭

**Comment by crimx** [comment]
是怎么用 chrome 打开，现在应该可以拦截才对。你是用了我发的 dist.zip 么。

**Comment by crimx** [comment]
能把路径的样子复制一下么，我测试了本地中文路径是没有问题的。

**Comment by crimx** [comment]
同时可以查看一下扩展选项的“默认用本扩展浏览 PDF”打开了没有。

**Comment by ljk8800** [comment]
打开了默认，但并没有默认用saladict打开

**Comment by ljk8800** [comment]
可以了，用重新关闭“默认用本扩展浏览 PDF”再打开一次“默认用本扩展浏览 PDF”才行

**Comment by ljk8800** [comment]
good job(￣▽￣)d 666

**Comment by crimx** [comment]
你点击这个链接会跳转到沙拉查词吗

http://kmmc.in/wp-content/uploads/2014/01/lesson2.pdf

**Comment by ljk8800** [comment]
会~prefect

**Comment by crimx** [comment]
好的
