### ISSUE TITLE
谷歌网页翻译跳转新标签页

### ISSUE THREAD

**Issue by ttttmr** [crimx/crx-saladict#21]
提几个建议

右键谷歌网页翻译的时候会跳转新标签页，不太方便，希望能在原页面直接显示翻译，就像有道网页翻译那样，如果也能实现分级翻译那就更好了

说到分级翻译，希望翻译级别能更细一点，比如四六级？

英语渣渣表示入门级还是有不少不认识的单词（这貌似是有道扩展的，可能不大好搞吧）

**Comment by crimx** [comment]
谷歌翻译是跳转到谷歌的网页进行翻译，如果这时关闭了当前网页，可能会丢失用户在输入的一些数据。这个功能是给其它浏览器用的，如果是用 Chrome 的话原生就支持谷歌网页翻译。

有道翻译功能是用了 http://fanyi.youdao.com/web2/ ，我只是修改了让它支持 https，所以翻译级别不受我控制。

**Comment by ttttmr** [comment]
嗯，我用的不是Chrome，发现Google翻译有出单独插件可以实现原页面翻译，这个能在沙拉里实现吗

https://chrome.google.com/webstore/detail/google-translate/aapbdbdomjkkjkaonfhkkikfgjllcleb

**Comment by crimx** [comment]
这个插件可以结合沙拉查词使用。

我修改有道是考虑了两个因素：1、它不支持 https ，这个相对容易修改（其实也不易，要扒混淆过的代码）；2、它很久没有更新了，接口稳定，维护成本不大。

谷歌有现成的就不必再造一遍轮子，而且它更新也勤快。
