### ISSUE TITLE
无法打开PDF文件

### ISSUE THREAD

**Issue by WEI-Jialiang** [crimx/crx-saladict#25]
- 平台：
Ubuntu 16.04.3 LTS
Chrome Version 62.0.3202.94 (Official Build) (64-bit)

- 类型：
选择View as PDF，打开PDF文件之后，PDF文件为0页
console 中显示： Failed to load file:///path/to/file.pdf: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.

- 重现：
使用Chrome打开《Metaprogramming Ruby》一书（约15.4MB,  262页），后选择View as PDF

- 问题
在View as PDF下，URL为chrome-extension://cdonnmffkdaoajfknoeeecmchibpmkmg/assets/pdf/web/viewer.html?file=file:///path/to/file.pdf时，无法正常打开PDF文件；
不在View as PDF下，URL以file:///开头时，连按三下Ctrl无法唤出翻译界面

**Comment by crimx** [comment]
有勾选了“允许访问本地文件”了么

**Comment by WEI-Jialiang** [comment]
原来如此，那个选项是在Extensions页面里面勾选的啊，感谢
