### ISSUE TITLE
默认展开剩余内容

### ISSUE THREAD

**Issue by fengcen** [crimx/crx-saladict#3]
提一个建议，因为有滚动条，所以，如果默认展开所有的内容，窗口大小还是没变，对用户来说没有什么影响，对于想查看更多内容的用户来说少了点击箭头这一步，所以，可以始终默认展开查词的内容，包括小窗口的内容也默认展开，或者加一个选项。

**Comment by crimx** [comment]
你把默认高度设得非常大就行
