### ISSUE TITLE
Search Mode 选成 “Hold Ctrl/⌘” 直接双击也会触发

### ISSUE THREAD

**Issue by junzh0u** [crimx/crx-saladict#4]
Bug 重现步骤：
1. 在一个页面 Hold 住 ⌘ 然后双击一个单词，查词框会弹出
2. 切换到别的页面
3. 切换回步骤 1 中的页面
4. 直接双击一个单词，**查词框依然会弹出**
5. *这时候按一次 ⌘ 键会恢复正常*
6. 但是重复 2. 3. 依然会触发 Bug

环境：
Chrome Version 60.0.3112.113 (Official Build) (64-bit)
macOS Sierra Version 10.12.6

**Comment by crimx** [comment]
looking into it

**Comment by crimx** [comment]
为了平台兼容性我是分别记录按下与松开 ⌘ 键的，所以按着 ⌘ 键切换到其它地方之后不能记录松开。Bug 已修复 [v5.15.12](https://github.com/crimx/crx-saladict/releases/tag/v5.15.12)。感谢反馈。
