### ISSUE TITLE
你好 关于部分网站不支持查词

### ISSUE THREAD

**Issue by xxxxxdog** [crimx/crx-saladict#7]
你好 谢谢你的插件 好可爱啊 很喜欢 。就是我发现newyorker似乎不支持查词 不知道为什么，请问有什么方法在newyorker上开启查词功能吗谢谢

**Comment by xxxxxdog** [comment]
还有一个小小的建议就是是否可能增加一个功能 快捷关闭查词  比如右键关闭 或者自动几秒关闭这样。

**Comment by crimx** [comment]
你能给个例子么，我上 https://www.newyorker.com/ 浏览没有发现问题的。点击右上的图标在最下面可以开关划词。太频繁的建议更换划词方式为按住 ctrl 查词。

**Comment by xxxxxdog** [comment]
你好 我刚刚又试了一遍发现是可以的 就是在前两天刚装插件的时候 划词没有sala小图标出现。谢谢你做这么好用的插件出来。

**Comment by crimx** [comment]
嗯，留意看简介，刚安装需要刷新已打开的页面以加载词典。
