### ISSUE TITLE
希望优化一下词典

### ISSUE THREAD

**Issue by ljhui** [crimx/crx-saladict#8]
试过几款翻译插件，沙拉查词感觉挺不错的，最近一直用，只是对词典感觉不满意，我中英文查询都常用，沙拉带的国语词典和两岸词典都只支持繁体中文，对简化字没有结果，希望在查询简体中文时，先自动转化为繁体在国语词典和两岸词典内查询，我是不介意看繁体的，或者你看看能不能添加汉典字典，我以前一直使用汉典网的汉典字典chrome插件来查询中文，好像还有一个快快查字典，我常在手机上用。

另外中英文都用，感觉方框内词典有点多，不知能否实现对特定语言使用特定词典，比如查英文用哪几部，查中文时用哪几部。

 希望插件越来越好！

**Comment by crimx** [comment]
我再看看怎么优化中文查词的体验……

**Comment by crimx** [comment]
[5.18.1](https://github.com/crimx/crx-saladict/releases/tag/v5.18.1) 修复了这三个问题，如果没问题的话就 close 掉这个 issue 吧:dancers:

1. 可配置词典只在某种语言下显示
2. 修复繁体词典不能查简体字问题
3. 增加汉典

**Comment by ljhui** [comment]
试了一下，挺好的，非常感谢！

**Comment by fobeetsai** [comment]
我常用中日詞典去查日文翻譯,可否追加幾個翻譯網站到『字典設定』內,雖然裡面的百度翻譯也很好用,
但建議追加
@有道詞典 http://fanyi.youdao.com/
@彩雲翻譯 https://fanyi.caiyunapp.com/#/
@騰訊翻譯君 https://fanyi.qq.com/
@お試し翻訳 https://miraitranslate.com/trial/
 麻煩您費心了 謝謝
FOBEE

**Comment by crimx** [comment]
翻译服务抓取难度很大，我再看看吧。

**Comment by fobeetsai** [comment]
謝謝您的回覆。若能成功的話、対於日文翻譯精度會有很大的提升、也能造福大群日文學習者、功德無量🙏。

從我的 iPhone 傳送

**Comment by crimx** [comment]
Saladict 不建议通过翻译来学习的。以现在的技术再好的翻译引擎也是很多错误。Saladict 中的翻译主要是为用户在做翻译时提供遣词造句的灵感。日语已有 Weblio 和 沪江小D 词典。

**Comment by fobeetsai** [comment]
您提點的問題點、我很認同。不過若能透過相対準度較高的翻譯引擎去做交相比対的話、會省很多時間、快速増進理解力、対於外語學習也能維持一定的動力。我長年從事日文教學、您研發的這個app是同時兼具聴、讀、查詢等多項功能、幫助了我很多的學生、在此致上謝意。但若加上我之前介紹的翻譯引擎進來、就更棒了。

從我的 iPhone 傳送

**Comment by crimx** [comment]
老师好，请问老师如何解决翻译失真的问题呢。学生利用机器翻译学习，如何甄别不符合实际用法的结果。Saladict 目前通过多个词典的解释以及句库模式中大量的真实语料来避免这个问题。

非常欢迎开新 issue 或邮件继续交流，就不占用这个 issue 打扰楼主了。

**Comment by fobeetsai** [comment]
您好：
我很榮幸能與您交流、我發現很多app都能部分解决我學生學習日語上的痛點、但都不能全面的解決、若您願意大発佛心、解決並縮短他們學習外語的盲點及痛苦、我願意貢獻我的一些意見並進行交流。我也有wechat,可在上面進行交流。

從我的 iPhone 傳送

**Comment by crimx** [comment]
@fobeetsai 好的，请加我的 [wechat](https://0bin.net/paste/f89-sunkq8I3KFyO#Cfq3zcLrfkuKkb4WjpPrw-BnqGYBw40V0W0qzZVLMRS)。
