### ISSUE TITLE
pdf中不能划词翻译

### ISSUE THREAD

**Issue by aizjq** [crimx/crx-saladict#9]
如题，还有就是有些网站不支持，msdn，codeProject等等
浏览器是centBrowser.版本 2.9.4.39（正式版本） （64 位） (portable) (Chromium 61.0.3163.100)

**Comment by crimx** [comment]
PDF 使用请看 Wiki 说明。不行的网站请提供链接。

**Comment by aizjq** [comment]
谢谢，浏览这个网站（https://www.codeproject.com），点击“碗装悬浮图标”弹出的界面秒闪

**Comment by crimx** [comment]
@aizjq 这个网站十分暴力地循环检测 iframe，所以基本无解。
